theme: jekyll-theme-cayman
title: wcdo2025
description: 2025 Workshop on Computationallly Designed Organisms
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
